name: End-to-End tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install Playwright Test
      run: yarn add @playwright/test
    - name: Install Playwright
      run: yarn playwright install --with-deps
    - name: Start development server
      run: yarn run dev &
      env:
        # Set environment variables for the development server
        NEXT_PUBLIC_GOOGLE_MAPS: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS }}
        NEXT_PUBLIC_GOOGLE_CALENDAR: ${{ secrets.NEXT_PUBLIC_GOOGLE_CALENDAR }}
        NEXT_PUBLIC_GOOGLE_CALENDAR_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CALENDAR_ID }}
        NEXT_PUBLIC_DELETE_EVENT: ${{ secrets.NEXT_PUBLIC_DELETE_EVENT }}
        NEXT_PUBLIC_EDIT_EVENT: ${{ secrets.NEXT_PUBLIC_EDIT_EVENT }}
        NEXT_PUBLIC_CLOUDINARY_CLOUDNAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUDNAME }}
        NEXT_PUBLIC_CLOUDINARY_UNSIGNED_UPLOAD_PRESET: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_UNSIGNED_UPLOAD_PRESET }}
        NEXT_PUBLIC_OPENWEATHERMAP: ${{ secrets.NEXT_PUBLIC_OPENWEATHERMAP }}
        NEXT_PUBLIC_BROWSE_ROBOT_ID: ${{ secrets.NEXT_PUBLIC_BROWSE_ROBOT_ID }}
        NEXT_PUBLIC_BROWSE_BEARER: ${{ secrets.NEXT_PUBLIC_BROWSE_BEARER }}
        KV_URL: ${{ secrets.KV_URL }}
        KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
        KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
        KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        SENTRY_IGNORE_API_RESOLUTION_ERROR: ${{ secrets.SENTRY_IGNORE_API_RESOLUTION_ERROR }}
        NEXT_PUBLIC_TINY: ${{ secrets.NEXT_PUBLIC_TINY }}
        NEXT_PUBLIC_SCRAPINGBEE: ${{ secrets.NEXT_PUBLIC_SCRAPINGBEE }}
    - name: Wait for server to be ready
      run: |
        echo "Waiting for server to be ready..."
        timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3001)" != "200" ]]; do sleep 5; done' || exit 1
    - name: Check server logs if wait fails
      if: failure()
      run: |
        echo "Server failed to start. Checking logs:"
        cat /home/runner/.npm/_logs/*-debug.log
    - name: Run Playwright tests
      run: npx playwright test --retries=2 --timeout=60000
      env:
        PLAYWRIGHT_BASE_URL: http://localhost:3001
        PLAYWRIGHT_TEST_TIMEOUT: 60000
