name: Lighthouse
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn && npm install -g @lhci/cli@0.12.0
      - run: yarn run vercel-build && lhci collect && lhci upload
        env:
          # If you app has any environment variables that
          # are required at build time, add them here:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
